version: 1
accounts:
  - name: alice
    coins:
      - 200000000stake
  - name: bob
    coins:
      - 999999999bto
      - 999999999kto
  - name: carl
    coins:
      - 200000000bto
      - 200000000kto
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100000bto
    - 100000kto
validators:
  - name: alice
    bonded: 100000000stake
